INSERT INTO Question_Choices
VALUES
('It indicates that a member belongs to the type itself, rather than to instances of the type',	5),
('It indicates that a method is an instance method.',	5),
('protected',	4),
('A database management system',	1),
('A programming language',	1),
('An application framework',	1),
('An operating system',	1),
('false',	6),
('false',	7),
('false',	8),
('false',	9),
('false',	10),
('global',	4),
('int variableName',	2),
('It indicates that a class cannot be inherited.',	5),
('It indicates that a variable can only be accessed within the same class.',	5),
('private',	4),
('public',	4),
('string variableName',	2),
('To create an object',	3),
('To declare a variable',	3),
('To define a new class',	3),
('To include a namespace',	3),
('True',	6),
('True',	7),
('True',	8),
('True',	9),
('True',	10),
('var variableName;',	2),
('variableName;',	2)